const tagNames={onsen:"温泉",bath:"大浴場",breakfast:"朝食",family:"子連れ",station:"駅近",budget:"予算控えめ",solo:"一人旅",lastminute:"直前",internet:"Wi-Fi",nonsmoking:"禁煙"};
const state={data:null,theme:"all",query:"",sort:"score",available:true,drafts:[]};
const $=(id)=>document.getElementById(id);

document.addEventListener("DOMContentLoaded",async()=>{bind();await load();});
function bind(){ $("query").addEventListener("input",e=>{state.query=e.target.value.trim().toLowerCase();render();});$("theme").addEventListener("change",e=>{state.theme=e.target.value;render();});$("sort").addEventListener("change",e=>{state.sort=e.target.value;render();});$("available").addEventListener("change",e=>{state.available=e.target.checked;render();});$("draftBtn").addEventListener("click",makeDraft);}
async function load(){const res=await fetch("data/hotels.json",{cache:"no-store"});state.data=await res.json();state.drafts=[...(state.data.drafts||[])];initThemes();render();}
function initThemes(){const select=$("theme");for(const t of state.data.themes||[])select.insertAdjacentHTML("beforeend",`<option value="${esc(t.id)}">${esc(t.label)}</option>`)}
function visible(){let hotels=[...(state.data.hotels||[])].filter(h=>{const text=[h.name,h.area,h.special,(h.tags||[]).join(" ")].join(" ").toLowerCase();if(state.theme!=="all"&&h.theme!==state.theme&&!(h.tags||[]).includes(state.theme))return false;if(state.available&&!h.available)return false;if(state.query&&!text.includes(state.query))return false;return true});hotels.sort((a,b)=>state.sort==="rating"?(b.reviewAverage||0)-(a.reviewAverage||0):state.sort==="price"?(a.minCharge||999999)-(b.minCharge||999999):(b.recommendationScore||0)-(a.recommendationScore||0));return hotels;}
function render(){const hotels=visible();$("count").textContent=`${hotels.length}件の宿候補`;renderSummary(hotels);$("cards").innerHTML=hotels.length?hotels.map(card).join(""):`<div class="empty">条件に合う宿が見つかりませんでした。</div>`;renderDrafts();}
function renderSummary(hotels){const avg=hotels.length?hotels.reduce((s,h)=>s+(h.reviewAverage||0),0)/hotels.length:0;const family=hotels.filter(h=>(h.tags||[]).includes("family")).length;const prices=hotels.map(h=>h.minCharge).filter(Boolean).sort((a,b)=>a-b);const med=prices.length?prices[Math.floor(prices.length/2)]:0;$("summary").innerHTML=`<div class="metric"><strong>${hotels.length}</strong><span>候補ホテル</span></div><div class="metric"><strong>${avg.toFixed(2)}</strong><span>平均レビュー</span></div><div class="metric"><strong>${family}</strong><span>子連れ候補</span></div><div class="metric"><strong>${yen(med)}</strong><span>中央値の料金目安</span></div>`;}
function card(h){const tags=(h.tags||[]).slice(0,5).map(t=>`<span class="tag">${esc(tagNames[t]||t)}</span>`).join("");return `<article class="hotel"><img src="${esc(h.imageUrl||"assets/hotel-placeholder.svg")}" alt="${esc(h.name)}"><div><h3>${esc(h.name)}</h3><p class="meta">${esc(h.area||"")} ${h.nearestStation?"/ "+esc(h.nearestStation)+"周辺":""}</p><p class="special">${esc(h.special||"")}</p><div class="tags">${tags}</div><div class="score"><div><small>レビュー評価</small><b>${num(h.reviewAverage)}</b></div><div><small>レビュー件数</small><b>${(h.reviewCount||0).toLocaleString("ja-JP")}件</b></div><div><small>空室候補</small><b>${h.availabilityCount||0}件</b></div></div></div><div><div class="price"><small>1泊1室あたり目安</small>${yen(h.minCharge)}〜</div><a class="btn" href="${esc(h.rakutenUrl||"https://travel.rakuten.co.jp/")}" target="_blank" rel="sponsored noopener">楽天トラベルで見る</a></div></article>`;}
function makeDraft(){const hotels=visible().slice(0,5);if(!hotels.length)return;const label=state.theme==="all"?"直前予約":($("theme").selectedOptions[0]?.textContent||state.theme);state.drafts.unshift({title:`${label}で探す高評価ホテル${hotels.length}選`,status:"レビュー待ち",hotelIds:hotels.map(h=>h.id),updatedAt:new Date().toISOString()});renderDrafts();}
function renderDrafts(){$("drafts").innerHTML=state.drafts.length?state.drafts.slice(0,8).map(d=>`<article class="draft"><b>${esc(d.title)}</b><p class="meta">${esc(d.status||"下書き")} / ${(d.hotelIds||[]).length}施設</p></article>`).join(""):`<p class="meta">下書きはまだありません。</p>`;}
function yen(v){return v?`${Number(v).toLocaleString("ja-JP")}円`:"確認"}function num(v){return v?Number(v).toFixed(2):"未取得"}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
